language: php
matrix:
  include:
    - php: 5.6
    - php: 5.5
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git
  - cd neos-base-distribution
  - git checkout 2.0.0
  - composer update
install:
  - mv ../SimplyAdmire.CrowdConnector Packages/Application
before_script:
  - echo 'date.timezone = "Europe/Amsterdam"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - bin/phpunit -c Packages/Application/SimplyAdmire.CrowdConnector/PhpUnit.xml
  - bin/phpunit --stop-on-failure -c Packages/Application/SimplyAdmire.CrowdConnector/PhpUnit.xml --testsuite "CrowdConnector tests"
