TYPO3:
  Neos:
    typoScript:
      autoInclude:
        SimplyAdmire.CrowdConnector: TRUE
  Flow:
    security:
      authentication:
        authenticationStrategy: atLeastOneToken
        providers:
          CrowdProvider:
            provider: SimplyAdmire\CrowdConnector\Provider\CrowdProvider
            providerOptions:
              crowdServerUrl: 'https://people.simplyadmire.com/crowd'
              password: '## DO NOT SET PASSWORD HERE! We do not want this in git! :) ##'
              applicationName: 'gemeenterijk'
              mode: ''

            entryPoint: WebRedirect
            entryPointOptions:
              routeValues:
                '@package': SimplyAdmire.CrowdConnector
                '@controller': Authentication
                '@action': login
                '@format': html